---
title: "xgboost"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(ranger)
library(iai)
library(intsurv)
library(survminer)
library(survival)
library(readr)
library(randomForestSRC)
library(ranger)
library(alabama)
library(dplyr)
library(rpart)
library(treeClust)
```

```{r}
IFM_data_continuous=read_csv("IFM_8_continuous.csv")[,-2]
IFM=IFM_data_continuous[,1:9]
MMRF_data_continuous=read_csv("MMRF_8_continuous.csv")[,-2]
MMRF=MMRF_data_continuous[,1:9]
Gamer_data_continuous=read_csv("Gamer_7_continuous.csv")
Gamer=Gamer_data_continuous[,c(1:7,10:11)]%>%
  rename(time=death1,status=deathE)
UAMS_data_continuous=read_csv("UAMS_8_continuous.csv")[,-2]
UAMS=UAMS_data_continuous[,1:9]%>%
  rename(time=OS,status=OS_censor)
```

```{r}
library(survival)
library(survXgboost)
library(xgboost)
library(intsurv)

train = UAMS
test = MMRF
train <- train[complete.cases(train), ] # doesn't handle missing values at the moment
test <- test[complete.cases(test), ]

label <- ifelse(train$status == 1, train$time, -train$time)
test_label <- ifelse(test$status == 1, test$time, -test$time)

val_ind <- sample.int(nrow(train), 0.3 * nrow(train))
x_train <- as.matrix(train[-val_ind, !names(train) %in% c("time", "status")])
x_label <- label[-val_ind]
x_val <- xgb.DMatrix(as.matrix(train[val_ind, !names(train) %in% c("time", "status")]),
                     label = label[val_ind])

x_test <- xgb.DMatrix(as.matrix(test[, !names(test) %in% c("time", "status")]),
                     label = test_label)

# train surv_xgboost
surv_xgboost_model <- xgb.train.surv(
  params = list(
    objective = "survival:cox",
    eval_metric = "cox-nloglik",
    eta = 0.05 # larger eta leads to algorithm not converging, resulting in NaN predictions
  ), data = x_train, label = x_label,
  watchlist = list(val2 = x_val),
  nrounds = 1000, early_stopping_rounds = 30
)

# predict survival curves
times <- seq(10, 1000, 50)
survival_curves <- predict(object = surv_xgboost_model, newdata = x_test, type = "surv", times = times)
matplot(times, t(survival_curves[1:5, ]), type = "l")

# predict risk score
risk_scores <- predict(object = surv_xgboost_model, newdata = x_test, type = "risk")
cIndex(test$time,test$status,as.vector(risk_scores))[1]
```

