---
title: "real data analysis experiment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
library(intsurv)
library(survminer)
library(survival)
library(readr)
library(randomForestSRC)
library(ranger)
library(alabama)
library(dplyr)
```

```{r}
setwd("./Gene\ signature\ scores")
EMC_score=read.csv("./EMC_score_IFM.csv")
EI_score=read.csv("./EI_OS_score_IFM.csv")
UAMS_score=read.csv("./UAMS70_score_IFM.csv")
GPI_score=read.csv("./GPI_score_IFM.csv")
```

```{r}
merged=merge(EMC_score,EI_score,by="patient")%>%
  rename(EMC=score,EI=OS_score)%>%
  merge(UAMS_score,by="patient")%>%
  rename(UAMS70=score)%>%
  merge(GPI_score,by="patient")%>%
  rename(GPI=score)
```

```{r}
library(dplyr)
IFM_Survival=read_csv("./Survival_IFM.csv")%>%
  dplyr::select("TTOS","Death","subjid","TTRelpase","Relapse")%>%
  rename(patient=subjid,time=TTOS,status=Death)
```
```{r}
merged_data=merge(merged,IFM_Survival,by="patient")
patient_ID=merged_data$patient
merged_data_IFM=merged_data[,-1]
write_csv(merged_data_IFM,"./merged_IFM_data_continuous_pfs.csv")
```

```{r}
setwd("./Gene\ signature\ scores")
UAMS17_score=read.csv("./UAMS17_score_IFM.csv")
UAMS80_score=read.csv("./UAMS80_score_IFM.csv")
HM19_score=read.csv("./HM19_score_IFM.csv")
IFM15_score=read.csv("./IFM15_score_IFM.csv")
```

```{r}
merged2=merge(merged,UAMS17_score,by="patient")%>%
  rename(UAMS17=score)%>%
  merge(UAMS80_score,by="patient")%>%
  rename(UAMS80=score)%>%
  merge(HM19_score,by="patient")%>%
  rename(HM19=score)%>%
  merge(IFM15_score,by="patient")%>%
  rename(IFM15=score)
```

```{r}
# merged_data2=merge(merged2,IFM_Survival,by="patient")
# patient_ID=merged2$patient
# merged_data_IFM2=merged_data2[,-1]
# write_csv(merged_data_IFM2,"./merged_IFM_scores.csv")
```

```{r}
binary=merged2
count=rep(0,nrow(binary))
for (i in 2:ncol(binary)){
  threshold=quantile(binary[,i],0.8)
  binary[,i]=ifelse(binary[,i]>threshold,1,0)
  count=count+binary[,i]
}
binary$count=count
```
```{r}
library(viridis)
positive_count=subset(binary,count>0)
positive_count=positive_count[order(positive_count$count, decreasing = TRUE), ]
barplot(positive_count$count)

long_df <- positive_count[,-10] |> pivot_longer(cols = colnames(positive_count)[-c(1,10)], names_to = "X", values_to = "Z")
long_df$patient=factor(long_df$patient,levels=unique(long_df$patient))
library(ggplot2)
long_df |> ggplot(aes(patient, X, fill = Z)) + geom_tile()+scale_fill_viridis()
```



```{r}
IFM=merge(binary,IFM_Survival,by="patient")
IFM$risk=ifelse(IFM$count>5,1,ifelse(IFM$count>2,2,3))

PFS_fit=survfit(Surv(TTRelpase,Relapse) ~ risk, data = IFM)
result=survdiff(Surv(TTRelpase,Relapse) ~ risk, data = IFM)
autoplot(PFS_fit,main="PFS of different risk groups in IFM categorized by \nthe number of signatures indicating high risk",conf.int = F)+
  ggplot2::annotate("text", x = 10, y = 0.01, label = paste0("pvalue: ", sprintf("%.2e", result$pvalue)) , size = 3, hjust = 0)+
  guides(fill=FALSE) +
  labs(colour = "Number") +
  scale_color_manual(labels = c("6,7,8", "3,4,5","0,1,2"), values = c(1, 2,3))

OS_fit=survfit(Surv(time,status) ~ risk, data = IFM)
result=survdiff(Surv(time,status) ~ risk, data = IFM)
autoplot(OS_fit,main="OS of different risk groups in IFM categorized by \nthe number of signatures indicating high risk",conf.int = F)+
  ggplot2::annotate("text", x = 10, y = 0.01, label = paste0("pvalue: ", sprintf("%.2e", result$pvalue)) , size = 3, hjust = 0)+
  guides(fill=FALSE) +
  labs(colour = "Numer") +
  scale_color_manual(labels = c("6,7,8", "3,4,5","0,1,2"), values = c(1, 2,3))
```

```{r}
del17p=read_csv("./DNA\ markers/cohort_export_baseline_del17p.csv")
delCDKN2C=read_csv("./DNA\ markers/cohort_export_baseline_delCDKN2C.csv")
gain1q21=read_csv("./DNA\ markers/cohort_export_baseline_gain1q21.csv")
delt414=read_csv("./DNA\ markers/cohort_export_baseline_t414.csv")
delt1416=read_csv("./DNA\ markers/cohort_export_baseline_t1416.csv")
```
```{r}
IFM$patient=gsub(pattern = "_",replacement = "",x = IFM$patient)
IFM$del17p=ifelse(IFM$patient %in% del17p$Patient,1,0)
IFM$delCDKN2C=ifelse(IFM$patient %in% delCDKN2C$Patient,1,0)
IFM$gain1q21=ifelse(IFM$patient %in% gain1q21$Patient,1,0)
IFM$delt414=ifelse(IFM$patient %in% delt414$Patient,1,0)
IFM$delt1416=ifelse(IFM$patient %in% delt1416$Patient,1,0)
```

```{r}
IFM=IFM[order(IFM$count, decreasing = TRUE), ]
long_df2 <- IFM[,c(1,16:20)] |> pivot_longer(cols = colnames(IFM)[16:20], names_to = "X", values_to = "Z")
long_df2$patient=factor(long_df2$patient,levels=unique(long_df2$patient))
long_df2 |> ggplot(aes(patient, X, fill = Z)) + geom_tile() +scale_fill_viridis()
```

Risk Table
```{r}
### This is a data frame with 3 columns,
### time: should be PFS or OS time depending your KM plot. Please convert your time to months if it is coded as days or years
### event: should be your censor information, by default 1 is event observed, 0 ins censor
### group: should be you sample groupings like mutation present vs. WT vs. deletion etc.
library(rawr)
IFM$risk=ifelse(IFM$count>5,1,ifelse(IFM$count>2,2,ifelse(IFM$count>0,3,4)))
survData <- IFM[,c(11,12,15)]
survData$time=survData$time/30.42
colnames(survData) <- c("Time","Event","Class")
table(survData$Class)

survData <- na.omit(survData)

### This function will create survival curves and create survfit object required for plotting below.
### It simply use the data frame generated above
surv.fit <- survfit (Surv(Time,Event)~ Class, data=survData)
paircomp_OS <- coxph_pairs(Surv(Time,Event)~ Class, data=survData)

### ggsurvplot funtion creates KM plot and risk table in JCO format. 
### Please do not change the palette option
### It takes survival curves and data table generated above
### If your data has a short follow up you may consider adjusting break.time.by = 6 to add a risk table entry for every 6 months instead of 12 months 
ggsurv <- ggsurvplot(
  surv.fit,                     # survfit object with calculated statistics.
  data = survData,             # data used to fit survival   curves.
  risk.table = TRUE,       # show risk table.
  tables.theme = clean_theme(),
  pval = TRUE,             # show p-value of log-rank test.
  pval.coord = c(-0.75,0.20),
  #  conf.int = TRUE,         # show confidence intervals for 
  # point estimates of survival curves.
  palette = "jco",
  # survival estimates.
  xlab = "Time in months",   # customize X axis label. 
  ylab = " OS probability",
  xlim = c(0,110),
  break.time.by = 12,     # break X axis in time intervals by 500.
  ggtheme = theme_light(), # customize plot and risk table with a theme.
  risk.table.y.text.col = T,# color risk table text annotations.
  risk.table.height = 0.25, # the height of the risk table
  risk.table.y.text = FALSE,# show bars instead of names in text annotations
  # in legend of risk table.
  conf.int.style = "step",  # customize style of confidence intervals
  surv.median.line = "hv",  # add the median survival pointer.
  legend.labs = c(">5 signatures","3-5 signatures","1-2 signatures","0 signatures"),    # change legend labels, please double check your edited labels here and your input data!!
  #palette = c("#CD534CFF","#0073C2FF","#EFC000FF","#6a994e")
)

### Double check your KM plot
print(ggsurv)
```
Risk Table for PFS
```{r}
### This is a data frame with 3 columns,
### time: should be PFS or OS time depending your KM plot. Please convert your time to months if it is coded as days or years
### event: should be your censor information, by default 1 is event observed, 0 ins censor
### group: should be you sample groupings like mutation present vs. WT vs. deletion etc.
library(rawr)
IFM$risk=ifelse(IFM$count>5,1,ifelse(IFM$count>2,2,ifelse(IFM$count>0,3,4)))
survData <- IFM[,c(13,14,15)]
colnames(survData) <- c("Time","Event","Class")
survData$Time=survData$Time/30.42
table(survData$Class)

survData <- na.omit(survData)

### This function will create survival curves and create survfit object required for plotting below.
### It simply use the data frame generated above
surv.fit <- survfit (Surv(Time,Event)~ Class, data=survData)
paircomp_OS <- coxph_pairs(Surv(Time,Event)~ Class, data=survData)

### ggsurvplot funtion creates KM plot and risk table in JCO format. 
### Please do not change the palette option
### It takes survival curves and data table generated above
### If your data has a short follow up you may consider adjusting break.time.by = 6 to add a risk table entry for every 6 months instead of 12 months 
ggsurv <- ggsurvplot(
  surv.fit,                     # survfit object with calculated statistics.
  data = survData,             # data used to fit survival   curves.
  risk.table = TRUE,       # show risk table.
  tables.theme = clean_theme(),
  pval = TRUE,             # show p-value of log-rank test.
  pval.coord = c(-0.75,0.20),
  #  conf.int = TRUE,         # show confidence intervals for 
  # point estimates of survival curves.
  palette = "jco",
  # survival estimates.
  xlab = "Time in months",   # customize X axis label. 
  ylab = " PFS probability",
  xlim = c(0,110),
  break.time.by = 12,     # break X axis in time intervals by 500.
  ggtheme = theme_light(), # customize plot and risk table with a theme.
  risk.table.y.text.col = T,# color risk table text annotations.
  risk.table.height = 0.25, # the height of the risk table
  risk.table.y.text = FALSE,# show bars instead of names in text annotations
  # in legend of risk table.
  conf.int.style = "step",  # customize style of confidence intervals
  surv.median.line = "hv",  # add the median survival pointer.
  legend.labs = c(">5 signatures","3-5 signatures","1-2 signatures","0 signatures"),    # change legend labels, please double check your edited labels here and your input data!!
  #palette = c("#CD534CFF","#0073C2FF","#EFC000FF","#6a994e")
)

### Double check your KM plot
print(ggsurv)
```

